# Generated by Django 3.2.17 on 2023-02-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busroute', '0001_create_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='route',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
